name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
					
      - name: Install dependencies & build
        run: |
              npm i
              npm run build
							
      - name: Add Npm Token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc
          ls -al
          cat ./.npmrc
				
    #   - name: Publish to npm repository
				# env:
    # 	  	NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
