# workflow名字
name: Publish to npm

# 触发条件：当 main 分支有 push 事件时触发
on:
  push:
    branches:
      - main

jobs:
  publish:
    # 在 Ubuntu 最新版本上运行作业
    runs-on: ubuntu-latest
    steps:
        # 使用 actions/checkout 检出当前代码
      - name: Checkout code
        uses: actions/checkout@v4

        # 设置 Node.js 环境
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

        # 安装项目依赖，并编译
      - name: Install dependencies & build
        run: |
	        npm i
	        npm run build

        # 添加access token到.npmrc
	  - name: Add Npm Token
	    run: |
			echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc
		    ls -al
		    cat ./.npmrc

        # 发布到 npm registry
      - name: Publish to npm repository
        run: npm publish
        env:
	        # 读取github的secrets变量，这里的NPM_TOKEN是前面设置的变量名
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
